alias: Charge Tesla on Excess Solar
trigger:
  - platform: state
    entity_id: sensor.energy_production
  - platform: state
    entity_id: sensor.energy_usage
condition:
  - condition: sun
    before: sunset
    after: sunrise
  - condition: state
    entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
    state: "on"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ states('sensor.energy_production') | int -
              states('sensor.energy_usage') | int >
              variables.excess_solar_threshold }}
          - condition: state
            entity_id: binary_sensor.denis_tesla_charging
            state: "off"
        sequence:
          - service: tesla_custom.api
            data:
              command: charge_start
          - service: notify.notify
            data:
              message: Tesla charging triggered, excess solar above 4KW ☀️
      - conditions:
          - condition: template
            value_template: >-
              {{ states('sensor.energy_production') | int -
              states('sensor.energy_usage') | int <=
              variables.excess_solar_threshold }}
          - condition: state
            entity_id: binary_sensor.denis_tesla_charging
            state: "on"
            for: "{{ variables.delay_duration }}"
        sequence:
          - service: tesla_custom.api
            data:
              command: charge_stop
          - service: notify.notify
            data:
              message: Tesla charging disabled, solar production is low ⛅
variables:
  excess_solar_threshold: 4000
  delay_duration:
    hours: 0
    minutes: 10
    seconds: 0
