alias: Charge Tesla on Excess Solar
trigger:
  - platform: time_pattern
    minutes: /5
condition:
  - condition: sun
    before: sunset
    after: sunrise
  - condition: state
    entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
    state: "on"
  - condition: template
    value_template: "{{ now().month >= 3 and now().month <= 10 }}"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ states('sensor.energy_production') | int - 
              states('sensor.energy_usage') | int >  3500 }}
          - condition: state
            entity_id: binary_sensor.denis_tesla_charging
            state: "off"
        sequence:
          - service: notify.notify
            data:
              message: Tesla charging triggered, excess solar above 4KW ☀️
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.denis_tesla_charger
      - conditions:
          - condition: template
            value_template: "{{ states('sensor.energy_production') | int < 2500 }}"
          - condition: state
            entity_id: binary_sensor.denis_tesla_charging
            state: "on"
          - condition: template
            value_template: "{{ states('sensor.denis_tesla_battery') | int >= 25 }}"
        sequence:
          - service: notify.notify
            data:
              message: Tesla charging disabled, solar production is low ⛅
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.denis_tesla_charger
